### ISSUE TITLE
About the CodeBlocks project file being screwed up

### ISSUE THREAD

**Issue by CodeBreadpudding** [TsjipTsjip/Bacon#3]
Try deleting it and then making a new project, then paste the code of bacon.c into a new bacon.c

**Comment by CodeBreadpudding** [comment]
On another note it probably isn't good for the project file to be uploaded in the first place.

**Comment by TsjipTsjip** [comment]
Illtry to fix it, if not this repository will be abandoned.

**~Closed~**
